# Generated by Django 4.0 on 2021-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('balck forest', 'Black Forest'), ('white forest', 'White Forest'), ('red velvet', 'Red Velvet'), ('chocolate', 'Chocolate')], max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
